name: Run Python Script

on:
  schedule:
    - cron: '*/2 * * * *' # Every 20 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-22.04
    environment: Test 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: content-file
        continue-on-error: true # In case there is no artifact from previous runs

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug List files
        run: ls -R

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: python script.py

      - name: Upload updated content file
        uses: actions/upload-artifact@v2
        with:
          name: content-file
          path: content_file.txt
