name: Run Python Script

on:
  schedule:
    - cron: '*/2 * * * *' # Every 2 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-22.04
    environment: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug List downloaded files
        run: ls -R # Verify files present after checkout

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: content_file_artifact
        continue-on-error: true # Allows workflow to proceed if artifact not found

      - name: Verify downloaded artifact
        run: cat content_file.txt || echo "No artifact found or file empty"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: python script.py

      - name: Upload updated content file
        uses: actions/upload-artifact@v4
        with:
          name: content_file_artifact
          path: content_file_artifact.txt
      
